#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 28 23:02:09 2020

@author: alex
"""

def linhas():
    print('-' * 85)


linhas()
print("Qual o valor da Função Soma?")
n1 = float(input(">_ "))
linhas()

p3 = 1.0 / (1.0 + 2.71828182846 ** n1)
print(p3)
